/**
 * Split Provider
 *
 * Load helpers and execute functions for splitting Canon Items and Aisles.
 * Called from api.ts only — never imported directly from UI.
 *
 * Split rules:
 * - Original record keeps its UUID; a new record is created.
 * - Nothing moves by default — caller provides an explicit list of what to move.
 * - Canon Items: user selects which recipe ingredient references move to new item.
 * - Aisles: user selects which canon items move to new aisle.
 */

import {
  collection,
  getDocs,
  writeBatch,
  where,
  query,
} from 'firebase/firestore';
import { db } from '../../../shared/backend/firebase';
import {
  reassignIngredientsByIds,
  reassignInstructionIngredientsByIds,
  collectIngredientRefs,
} from '../logic/merge';
import { createCanonItem, createCanonAisle } from './firebase-provider';
import { upsertCanonItemEmbeddingById } from './embeddings-provider';
import { suggestCofidForCanonItem } from './firebase-provider';

// ── Collection constants ───────────────────────────────────────────────────────

const CANON_ITEMS_COLLECTION = 'canonItems';
const EMBEDDING_LOOKUP_COLLECTION = 'canonEmbeddingLookup';
const RECIPES_COLLECTION = 'recipes';

// ── Types ─────────────────────────────────────────────────────────────────────

/** A single recipe ingredient reference, enriched with its recipe's title. */
export interface IngredientRef {
  recipeId: string;
  recipeTitle: string;
  ingredientId: string;   // The ingredient's own `id` field
  raw: string;            // Original recipe text e.g. "200g chicken breast, diced"
  ingredientName: string; // Parsed name e.g. "chicken breast"
}

export interface CanonItemSplitDef {
  name: string;
  aisleId: string;
  preferredUnitId: string;
}

export interface AisleSplitDef {
  name: string;
  sortOrder: number;
}

// ── Load helpers ───────────────────────────────────────────────────────────────

/**
 * Scan all recipes and return every ingredient reference to a given canon item,
 * enriched with the recipe title so the user can make an informed assignment.
 */
export async function getCanonItemIngredientRefs(
  canonItemId: string
): Promise<IngredientRef[]> {
  const recipesSnap = await getDocs(collection(db, RECIPES_COLLECTION));
  const refs: IngredientRef[] = [];

  for (const recipeDoc of recipesSnap.docs) {
    const data = recipeDoc.data();
    const recipeId = recipeDoc.id;
    const recipeTitle: string = data.title ?? data.name ?? 'Untitled recipe';

    const matches = collectIngredientRefs(
      data.ingredients ?? [],
      data.instructions ?? [],
      canonItemId
    );

    for (const ing of matches) {
      if (!ing.id) continue; // skip if ingredient has no own id
      refs.push({
        recipeId,
        recipeTitle,
        ingredientId: ing.id as string,
        raw: (ing.raw as string) ?? '',
        ingredientName: (ing.ingredientName as string) ?? '',
      });
    }
  }

  return refs;
}

// ── Execute functions ──────────────────────────────────────────────────────────

/**
 * Split a canon item.
 *
 * Creates a new canon item and re-links the specified ingredient references
 * (identified by their own ingredient `id`) to it. The original item is unchanged.
 *
 * @param originalId  The canon item being split (keeps its UUID)
 * @param newItemDef  Name, aisle, and unit for the new item
 * @param moveIngredientIds  Set of ingredient IDs (ingredient.id) to move to the new item
 * @returns The new canon item's ID
 */
export async function splitCanonItem(
  originalId: string,
  newItemDef: CanonItemSplitDef,
  moveIngredientIds: Set<string>
): Promise<string> {
  // 1. Create the new canon item (embedding generated by createCanonItem)
  const newItem = await createCanonItem({
    name: newItemDef.name,
    aisleId: newItemDef.aisleId,
    preferredUnitId: newItemDef.preferredUnitId,
    needsReview: false, // user is explicitly creating it
  });

  // 2. Fire-and-forget CoFID suggestion
  suggestCofidForCanonItem(newItem.id).catch(() => {});

  if (moveIngredientIds.size === 0) return newItem.id;

  // 3. Scan recipes and re-link selected ingredients
  const recipesSnap = await getDocs(collection(db, RECIPES_COLLECTION));
  const BATCH_SIZE = 499;
  let batch = writeBatch(db);
  let batchCount = 0;

  for (const recipeDoc of recipesSnap.docs) {
    const data = recipeDoc.data();

    const ingResult = reassignIngredientsByIds(
      data.ingredients ?? [],
      moveIngredientIds,
      newItem.id
    );
    const stepResult = reassignInstructionIngredientsByIds(
      data.instructions ?? [],
      moveIngredientIds,
      newItem.id
    );

    if (ingResult.changed || stepResult.changed) {
      batch.update(recipeDoc.ref, {
        ingredients: ingResult.patched,
        instructions: stepResult.patched,
      });
      batchCount++;
      if (batchCount >= BATCH_SIZE) {
        await batch.commit();
        batch = writeBatch(db);
        batchCount = 0;
      }
    }
  }

  if (batchCount > 0) await batch.commit();

  return newItem.id;
}

/**
 * Split an aisle.
 *
 * Creates a new aisle and moves the specified canon items (by ID) into it.
 * Also updates canonEmbeddingLookup entries for moved items.
 * The original aisle is unchanged.
 *
 * @param newAisleDef  Name and sortOrder for the new aisle
 * @param moveCanonItemIds  IDs of canon items to move to the new aisle
 * @returns The new aisle's ID
 */
export async function splitCanonAisle(
  newAisleDef: AisleSplitDef,
  moveCanonItemIds: string[]
): Promise<string> {
  // 1. Create the new aisle
  const newAisle = await createCanonAisle({
    name: newAisleDef.name,
    sortOrder: newAisleDef.sortOrder,
  });

  if (moveCanonItemIds.length === 0) return newAisle.id;

  const idSet = new Set(moveCanonItemIds);
  const BATCH_SIZE = 499;

  // 2. Update canonItems for selected items
  const itemsSnap = await getDocs(collection(db, CANON_ITEMS_COLLECTION));
  let batch = writeBatch(db);
  let count = 0;

  for (const d of itemsSnap.docs) {
    if (!idSet.has(d.id)) continue;
    batch.update(d.ref, { aisleId: newAisle.id });
    count++;
    if (count >= BATCH_SIZE) {
      await batch.commit();
      batch = writeBatch(db);
      count = 0;
    }
  }
  if (count > 0) await batch.commit();

  // 3. Update canonEmbeddingLookup for moved items
  const embSnap = await getDocs(
    query(collection(db, EMBEDDING_LOOKUP_COLLECTION))
  );
  let embBatch = writeBatch(db);
  let embCount = 0;

  for (const d of embSnap.docs) {
    const data = d.data();
    if (data.kind === 'canon' && idSet.has(data.refId)) {
      embBatch.update(d.ref, { aisleId: newAisle.id });
      embCount++;
      if (embCount >= BATCH_SIZE) {
        await embBatch.commit();
        embBatch = writeBatch(db);
        embCount = 0;
      }
    }
  }
  if (embCount > 0) await embBatch.commit();

  return newAisle.id;
}
